server:
  port: 9443
  ssl:
    certificate: ${HOME}/.config/devcerts/local.dev.swedenconnect.se-cert.pem
    certificate-private-key: ${HOME}/.config/devcerts/local.dev.swedenconnect.se-key.pem

spring:
  ssl:
    bundle:
      pem:
        rest:
          truststore:
            # certificate path works in local sc-environment if the repos are located side by side
            # otherwise: set the filepath with SPRING_SSL_BUNDLE_PEM_REST_TRUSTSTORE_CERTIFICATE environment variable
            certificate: "file:../eudiw-prototype/sc-environment/config/common/tls.crt"
            
eudiw:
  issuerBaseUrl: https://local.dev.swedenconnect.se:9090
  credentialHost: https://local.dev.swedenconnect.se:9090
  clientId: 1234567890
  # eudiw-client
  testServerBaseUrl:  https://local.dev.swedenconnect.se:9443
